integration_tests_invalid_configs:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"

  outputs:
    dev:
      type: duckdb
      path: integration_tests_invalid_configs.duckdb
      threads: 1
    postgres:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | as_number }}"
      user: "{{ env_var('POSTGRES_USER', 'dbt_checks') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'dbt_checks') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'dbt_checks') }}"
      schema: "{{ env_var('POSTGRES_SCHEMA', 'public') }}"
      threads: 1
    bigquery:
      type: bigquery
      method: service-account
      project: "{{ env_var('BIGQUERY_PROJECT', '') }}"
      dataset: "{{ env_var('BIGQUERY_DATASET', 'dbt_checks') }}"
      keyfile: "{{ env_var('BIGQUERY_KEYFILE', '') }}"
      location: "{{ env_var('BIGQUERY_LOCATION', 'US') }}"
      threads: 1
    snowflake:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', '') }}"
      user: "{{ env_var('SNOWFLAKE_USER', '') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', '') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', '') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'dbt_checks') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', '') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'public') }}"
      threads: 1