name: integration_tests
version: "1.0"
config-version: 2

profile: dbt_checks

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

packages-install-path: "{{ env_var('DBT_PACKAGES_INSTALL_PATH', 'dbt_packages') }}"

target-path: "target"
clean-targets:
  - "target"
  - "{{ env_var('DBT_PACKAGES_INSTALL_PATH', 'dbt_packages') }}"